#服务端口
server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: Product-Service
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/cooltiger?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.kyj.cooltiger.cooltigerproduct.entity

logging:
  level:
    com:
      kyj:
        cooltiger:
          cooltigergoods:
            mapper: debug