#服务端口
server:
  port: 8902

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: Product-Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://36.133.141.6:3306/cooltiger?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: kyj@cool.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #文件上传器
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.kyj.cooltiger.product.entity

#日志
logging:
  level:
    com:
      kyj:
        cooltiger:
          product:
            mapper: debug


#ftp
FTP:
  ADDRESS: 36.133.141.6
  PORT: 21
  USERNAME: ftpuser
  PASSWORD: kyj@ftp#123456
  BASEPATH: /home/ftpuser/images

#图片服务器
IMAGE:
  BASE:
    URL: http://36.133.141.6:81/images

