#服务端口号
server:
  port: 8888
  servlet:
    context-path: /eureka/

spring:
  application:
    name: Eureka-Service

#eureka基本信息配置
eureka:
  instance:
    hostname: localhost
    #hostname: 36.133.141.6 #注册中心ip
  client:
    #是否将自己注册到eureka
    register-with-eureka: true
    #是否从eureka获取注册信息
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/eureka/
  server:
    #关闭自我保护
    enable-self-preservation: false
