#服务端口
server:
  port: 8894

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: Feign-Consumer
  main:
    allow-bean-definition-overriding: true

ribbon:
  eureka:
    enabled: true