#服务端口
server:
  port: 8904

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: Order-Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://36.133.141.6:3306/cooltiger?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: kyj@cool.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.kyj.cooltiger.order.entity

logging:
  level:
    com:
      kyj:
        cooltiger:
          order:
            mapper: debug