#服务端口
server:
  port: 8804

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/eureka/

spring:
  application:
    name: Customer-Service
  main:
    allow-bean-definition-overriding: true
  #MYSQL数据源
  datasource:
    url: jdbc:mysql://36.133.141.6:3306/cooltiger?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: kyj@cool.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #文件上传器
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #Redis
  redis:
    database: 0
    host: 36.133.141.6
    port: 6379
    password: kyj@redis.123456

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.kyj.cooltiger.customer.entity

logging:
  level:
    com:
      kyj:
        cooltiger:
          customer:
            mapper: debug

#ftp
FTP:
  ADDRESS: 36.133.141.6
  PORT: 21
  USERNAME: ftpuser
  PASSWORD: kyj@ftp#123456
  BASEPATH: /home/ftpuser/images

#图片服务器
IMAGE:
  BASE:
    URL: http://cool.coolyouji.com/images

