#服务端口
server:
  port: 8890

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/eureka/

spring:
  application:
    name: Gateway-Service
  #Redis
  redis:
    database: 2
    host: 36.133.141.6
    port: 6379
    password: kyj@redis.123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          lowerCaseServiceId: true   # 该配置开启后，服务名可以小写
      #路由
      routes:
        - id: eureka  #路由id标识
          uri: lb://Eureka-Service  #请求转发地址
          predicates:  #断言
            - Path=/eureka/**  #匹配规则
        - id: oauth
          uri: lb://Oauth-Service
          predicates:
            - Path=/api/**
        - id: product
          uri: lb://Product-Service
          predicates:
            - Path=/product/**
        - id: order
          uri: lb://Order-Service
          predicates:
            - Path=/order/**
        - id: customer
          uri: lb://Customer-Service
          predicates:
            - Path=/customer/**
